#!/bin/bash
#首先获取网卡的名称，虽然我接触到的绝大多数情况下都是eth0，但是以防万一，还是判断一下。
netcard=$(ip addr | grep dynamic | awk '{print $9}' )      
#在获取到网卡名称之后，根据网卡名来获取对应的IP地址，掩码长度.
ipinfo=$(ip addr | grep $netcard | tail -n 1 | awk '{print $2}')
ip=$(echo $ipinfo | cut -d'/' -f1)
length=$(echo $ipinfo| cut -d'/' -f2)
mask=$( ifconfig $netcard | grep netmask | awk '{print $4}' )
#接下来根据IP和掩码求出所在网段.关于求所在网段这里我没想到有什么好的方法，查找资料也没有找到很简便的方式，所以这里就使用IP和掩码的异或来计算网段。
ip1=$( echo $ip | cut -d'.' -f1 )
ip2=$( echo $ip | cut -d'.' -f2 )
ip3=$( echo $ip | cut -d'.' -f3 )
ip4=$( echo $ip | cut -d'.' -f4 )
mask1=$( echo $mask | cut -d'.' -f1 )
mask2=$( echo $mask | cut -d'.' -f2 )
mask3=$( echo $mask | cut -d'.' -f3 )
mask4=$( echo $mask | cut -d'.' -f4 )
ips1=$(($ip1&$mask1))
ips2=$(($ip2&$mask2))
ips3=$(($ip3&$mask3))
ips4=$(($ip4&$mask4))

ips=$(echo $ips1.$ips2.$ips3.$ips4)
#到这里为止，我们所需要的条件已经齐了，可以开始扫描了
#获取主机IP列表
nmap -sP $ips/$length -oN ~/Scan/resault.txt
cat ~/Scan/resault.txt | grep report | awk '{print $5}' >> ~/Scan/hostlist
#获取主机数量
hostnum=$( cat ~/Scan/resault.txt | grep done | awk '{print $14}' | cut -d'(' -f2 )
echo "There are $hostnum hosts in this network" >> ~/Scan/hostlist
#主机的IP有了，开始端口以及操作系统扫描
for ipt in $( cat ~/Scan/hostlist )
do
  	nmap -O $ipt -oN ~/Scan/$ipt
done
